name: "CI (Integração Continua): Primeira action"

on:
    push:
        branches: ["main"]
    pull_request:
        type: [opened, synchronize]
    workflow_dispatch:

jobs:
    exemplo:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: "Exemplo"
              run: echo "Ola mundo!"
            - name: "Rua a list files"
              run: ls -la
